[project]
name = "panda-tg-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptg~=0.6.0",
    "hurry-filesize>=0.9",
    "loguru>=0.7.3",
    "numba>=0.67.0",
    "opencv-contrib-python-headless>=5.0.0.93",
    "pillow>=12.3.0",
    "python-socks[asyncio]>=2.0",
    "scipy>=1.18.1",
    "telethon>=1.38",
]
